Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 400, in <module>
    pdfs, metrics = run_experiment(
                    ^^^^^^^^^^^^^^^
  File "/oscar/scratch/daggarw5/fourier-head/toy-example-synthetic/scripts/toy_synthetic_mle.py", line 247, in run_experiment
    train_dataset = TensorDataset(X_train, y_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
           ^^^^
  File "/users/daggarw5/.conda/envs/chronos-doover/lib/python3.11/site-packages/torch/utils/data/dataset.py", line 206, in <genexpr>
    tensors[0].size(0) == tensor.size(0) for tensor in tensors
    ^^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not callable
slurmstepd: error: *** JOB 7593250 ON gpu2261 CANCELLED AT 2025-01-11T04:23:29 ***
